# Generated by Django 4.2.3 on 2023-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_used_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="last used ip"
            ),
        ),
    ]
