FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir poetry
RUN pip3 install debugpy

COPY pyproject.toml /app/
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi --with dev

COPY ./src /app